package com.wscloudclass.mapper;

import com.wscloudclass.model.CourseResourcesExample;
import com.wscloudclass.model.CourseResourcesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_resources
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    long countByExample(CourseResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_resources
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    int deleteByExample(CourseResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_resources
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    int deleteByPrimaryKey(CourseResourcesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_resources
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    int insert(CourseResourcesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_resources
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    int insertSelective(CourseResourcesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_resources
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    List<CourseResourcesKey> selectByExample(CourseResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_resources
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") CourseResourcesKey record, @Param("example") CourseResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_resources
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    int updateByExample(@Param("record") CourseResourcesKey record, @Param("example") CourseResourcesExample example);
}