package com.wscloudclass.mapper;

import com.wscloudclass.model.DownloadResources;
import com.wscloudclass.model.DownloadResourcesExample;
import com.wscloudclass.model.DownloadResourcesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DownloadResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_resources
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    long countByExample(DownloadResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_resources
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    int deleteByExample(DownloadResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_resources
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    int deleteByPrimaryKey(DownloadResourcesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_resources
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    int insert(DownloadResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_resources
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    int insertSelective(DownloadResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_resources
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    List<DownloadResources> selectByExampleWithRowbounds(DownloadResourcesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_resources
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    List<DownloadResources> selectByExample(DownloadResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_resources
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    DownloadResources selectByPrimaryKey(DownloadResourcesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_resources
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") DownloadResources record, @Param("example") DownloadResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_resources
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    int updateByExample(@Param("record") DownloadResources record, @Param("example") DownloadResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_resources
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    int updateByPrimaryKeySelective(DownloadResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_resources
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    int updateByPrimaryKey(DownloadResources record);
}