package com.wscloudclass.mapper;

import com.wscloudclass.model.JoinCourseExample;
import com.wscloudclass.model.JoinCourseKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JoinCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table join_course
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    long countByExample(JoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table join_course
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    int deleteByExample(JoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table join_course
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    int deleteByPrimaryKey(JoinCourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table join_course
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    int insert(JoinCourseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table join_course
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    int insertSelective(JoinCourseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table join_course
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    List<JoinCourseKey> selectByExample(JoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table join_course
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") JoinCourseKey record, @Param("example") JoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table join_course
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    int updateByExample(@Param("record") JoinCourseKey record, @Param("example") JoinCourseExample example);
}