package com.wscloudclass.mapper;

import com.wscloudclass.model.PartiActivity;
import com.wscloudclass.model.PartiActivityExample;
import com.wscloudclass.model.PartiActivityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartiActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parti_activity
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    long countByExample(PartiActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parti_activity
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    int deleteByExample(PartiActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parti_activity
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    int deleteByPrimaryKey(PartiActivityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parti_activity
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    int insert(PartiActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parti_activity
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    int insertSelective(PartiActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parti_activity
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    List<PartiActivity> selectByExample(PartiActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parti_activity
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    PartiActivity selectByPrimaryKey(PartiActivityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parti_activity
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") PartiActivity record, @Param("example") PartiActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parti_activity
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    int updateByExample(@Param("record") PartiActivity record, @Param("example") PartiActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parti_activity
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    int updateByPrimaryKeySelective(PartiActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parti_activity
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    int updateByPrimaryKey(PartiActivity record);
}