package com.wscloudclass.mapper;

import com.wscloudclass.model.SelectActivity;
import com.wscloudclass.model.SelectActivityExample;
import com.wscloudclass.model.SelectActivityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SelectActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_activity
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    long countByExample(SelectActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_activity
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    int deleteByExample(SelectActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_activity
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    int deleteByPrimaryKey(SelectActivityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_activity
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    int insert(SelectActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_activity
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    int insertSelective(SelectActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_activity
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    List<SelectActivity> selectByExample(SelectActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_activity
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    SelectActivity selectByPrimaryKey(SelectActivityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_activity
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") SelectActivity record, @Param("example") SelectActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_activity
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    int updateByExample(@Param("record") SelectActivity record, @Param("example") SelectActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_activity
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    int updateByPrimaryKeySelective(SelectActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_activity
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    int updateByPrimaryKey(SelectActivity record);
}