package com.wscloudclass.mapper;

import com.wscloudclass.model.UserFavExample;
import com.wscloudclass.model.UserFavKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    long countByExample(UserFavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    int deleteByExample(UserFavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    int deleteByPrimaryKey(UserFavKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    int insert(UserFavKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    int insertSelective(UserFavKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    List<UserFavKey> selectByExample(UserFavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserFavKey record, @Param("example") UserFavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    int updateByExample(@Param("record") UserFavKey record, @Param("example") UserFavExample example);
}