package com.wscloudclass.model;

import java.util.Date;

public class Activity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.act_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Long actId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_name
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private String activityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.act_type
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Integer actType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.start_time
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_time
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.des_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Long desId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.cid
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Long cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.act_id
     *
     * @return the value of activity.act_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Long getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.act_id
     *
     * @param actId the value for activity.act_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setActId(Long actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_name
     *
     * @return the value of activity.activity_name
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_name
     *
     * @param activityName the value for activity.activity_name
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.act_type
     *
     * @return the value of activity.act_type
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Integer getActType() {
        return actType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.act_type
     *
     * @param actType the value for activity.act_type
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setActType(Integer actType) {
        this.actType = actType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_time
     *
     * @return the value of activity.start_time
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_time
     *
     * @param startTime the value for activity.start_time
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_time
     *
     * @return the value of activity.end_time
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_time
     *
     * @param endTime the value for activity.end_time
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.des_id
     *
     * @return the value of activity.des_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Long getDesId() {
        return desId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.des_id
     *
     * @param desId the value for activity.des_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setDesId(Long desId) {
        this.desId = desId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.cid
     *
     * @return the value of activity.cid
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.cid
     *
     * @param cid the value for activity.cid
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }
}