package com.wscloudclass.model;

public class CompleteSignInKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complete_sign_in.uid
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complete_sign_in.sign_id
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    private Long signId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complete_sign_in.uid
     *
     * @return the value of complete_sign_in.uid
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complete_sign_in.uid
     *
     * @param uid the value for complete_sign_in.uid
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complete_sign_in.sign_id
     *
     * @return the value of complete_sign_in.sign_id
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    public Long getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complete_sign_in.sign_id
     *
     * @param signId the value for complete_sign_in.sign_id
     *
     * @mbg.generated Sun Feb 09 14:40:32 CST 2020
     */
    public void setSignId(Long signId) {
        this.signId = signId;
    }
}