package com.wscloudclass.model;

public class CourseResourcesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_resources.cid
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    private Long cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_resources.resource_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    private Long resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_resources.cid
     *
     * @return the value of course_resources.cid
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_resources.cid
     *
     * @param cid the value for course_resources.cid
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_resources.resource_id
     *
     * @return the value of course_resources.resource_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_resources.resource_id
     *
     * @param resourceId the value for course_resources.resource_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }
}