package com.wscloudclass.model;

public class Description {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.des_id
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    private Long desId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.des_content
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    private String desContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.file_name
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.file_url
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.file_size
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    private Integer fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.score
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.des_id
     *
     * @return the value of description.des_id
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public Long getDesId() {
        return desId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.des_id
     *
     * @param desId the value for description.des_id
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public void setDesId(Long desId) {
        this.desId = desId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.des_content
     *
     * @return the value of description.des_content
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public String getDesContent() {
        return desContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.des_content
     *
     * @param desContent the value for description.des_content
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public void setDesContent(String desContent) {
        this.desContent = desContent == null ? null : desContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.file_name
     *
     * @return the value of description.file_name
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.file_name
     *
     * @param fileName the value for description.file_name
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.file_url
     *
     * @return the value of description.file_url
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.file_url
     *
     * @param fileUrl the value for description.file_url
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.file_size
     *
     * @return the value of description.file_size
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.file_size
     *
     * @param fileSize the value for description.file_size
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.score
     *
     * @return the value of description.score
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.score
     *
     * @param score the value for description.score
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}