package com.wscloudclass.model;

public class DownloadResourcesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column download_resources.uid
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column download_resources.resource_id
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private Long resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column download_resources.uid
     *
     * @return the value of download_resources.uid
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column download_resources.uid
     *
     * @param uid the value for download_resources.uid
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column download_resources.resource_id
     *
     * @return the value of download_resources.resource_id
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column download_resources.resource_id
     *
     * @param resourceId the value for download_resources.resource_id
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }
}