package com.wscloudclass.model;

public class FileScoreKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_score.des_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Long desId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_score.file_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Long fileId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_score.des_id
     *
     * @return the value of file_score.des_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Long getDesId() {
        return desId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_score.des_id
     *
     * @param desId the value for file_score.des_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setDesId(Long desId) {
        this.desId = desId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_score.file_id
     *
     * @return the value of file_score.file_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_score.file_id
     *
     * @param fileId the value for file_score.file_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }
}