package com.wscloudclass.model;

public class FileScore extends FileScoreKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_score.score
     *
     * @mbg.generated Tue Feb 11 11:31:18 CST 2020
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_score.score
     *
     * @return the value of file_score.score
     *
     * @mbg.generated Tue Feb 11 11:31:18 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_score.score
     *
     * @param score the value for file_score.score
     *
     * @mbg.generated Tue Feb 11 11:31:18 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}