package com.wscloudclass.model;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    private Long messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_content
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    private String messageContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_time
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_check
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    private Integer isCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    private Long sendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.to_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    private Long toId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_id
     *
     * @return the value of message.message_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_id
     *
     * @param messageId the value for message.message_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_content
     *
     * @return the value of message.message_content
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_content
     *
     * @param messageContent the value for message.message_content
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_time
     *
     * @return the value of message.send_time
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_time
     *
     * @param sendTime the value for message.send_time
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_check
     *
     * @return the value of message.is_check
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public Integer getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_check
     *
     * @param isCheck the value for message.is_check
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public void setIsCheck(Integer isCheck) {
        this.isCheck = isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_id
     *
     * @return the value of message.send_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public Long getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_id
     *
     * @param sendId the value for message.send_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public void setSendId(Long sendId) {
        this.sendId = sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.to_id
     *
     * @return the value of message.to_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public Long getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.to_id
     *
     * @param toId the value for message.to_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public void setToId(Long toId) {
        this.toId = toId;
    }
}