package com.wscloudclass.model;

public class PartiActivityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parti_activity.uid
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parti_activity.act_id
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private Long actId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parti_activity.uid
     *
     * @return the value of parti_activity.uid
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parti_activity.uid
     *
     * @param uid the value for parti_activity.uid
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parti_activity.act_id
     *
     * @return the value of parti_activity.act_id
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public Long getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parti_activity.act_id
     *
     * @param actId the value for parti_activity.act_id
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setActId(Long actId) {
        this.actId = actId;
    }
}