package com.wscloudclass.model;

public class SelectActivityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_activity.act_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    private Long actId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_activity.sel_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    private Long selId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_activity.act_id
     *
     * @return the value of select_activity.act_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public Long getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_activity.act_id
     *
     * @param actId the value for select_activity.act_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public void setActId(Long actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_activity.sel_id
     *
     * @return the value of select_activity.sel_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public Long getSelId() {
        return selId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_activity.sel_id
     *
     * @param selId the value for select_activity.sel_id
     *
     * @mbg.generated Tue Feb 04 14:42:21 CST 2020
     */
    public void setSelId(Long selId) {
        this.selId = selId;
    }
}