package com.wscloudclass.model;

public class SelectActivity extends SelectActivityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_activity.sel_num
     *
     * @mbg.generated Tue Feb 11 11:31:18 CST 2020
     */
    private Integer selNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_activity.sel_num
     *
     * @return the value of select_activity.sel_num
     *
     * @mbg.generated Tue Feb 11 11:31:18 CST 2020
     */
    public Integer getSelNum() {
        return selNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_activity.sel_num
     *
     * @param selNum the value for select_activity.sel_num
     *
     * @mbg.generated Tue Feb 11 11:31:18 CST 2020
     */
    public void setSelNum(Integer selNum) {
        this.selNum = selNum;
    }
}