package com.wscloudclass.model;

public class Selection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.sel_id
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private Long selId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.sel_content
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private String selContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.img_url
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.a
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private String a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.b
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private String b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.c
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private String c;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.d
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private String d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.sel_ana
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private String selAna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.score
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.correct_option
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    private String correctOption;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.sel_id
     *
     * @return the value of selection.sel_id
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public Long getSelId() {
        return selId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.sel_id
     *
     * @param selId the value for selection.sel_id
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setSelId(Long selId) {
        this.selId = selId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.sel_content
     *
     * @return the value of selection.sel_content
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public String getSelContent() {
        return selContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.sel_content
     *
     * @param selContent the value for selection.sel_content
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setSelContent(String selContent) {
        this.selContent = selContent == null ? null : selContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.img_url
     *
     * @return the value of selection.img_url
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.img_url
     *
     * @param imgUrl the value for selection.img_url
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.a
     *
     * @return the value of selection.a
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.a
     *
     * @param a the value for selection.a
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setA(String a) {
        this.a = a == null ? null : a.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.b
     *
     * @return the value of selection.b
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public String getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.b
     *
     * @param b the value for selection.b
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setB(String b) {
        this.b = b == null ? null : b.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.c
     *
     * @return the value of selection.c
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public String getC() {
        return c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.c
     *
     * @param c the value for selection.c
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setC(String c) {
        this.c = c == null ? null : c.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.d
     *
     * @return the value of selection.d
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.d
     *
     * @param d the value for selection.d
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setD(String d) {
        this.d = d == null ? null : d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.sel_ana
     *
     * @return the value of selection.sel_ana
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public String getSelAna() {
        return selAna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.sel_ana
     *
     * @param selAna the value for selection.sel_ana
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setSelAna(String selAna) {
        this.selAna = selAna == null ? null : selAna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.score
     *
     * @return the value of selection.score
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.score
     *
     * @param score the value for selection.score
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.correct_option
     *
     * @return the value of selection.correct_option
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public String getCorrectOption() {
        return correctOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.correct_option
     *
     * @param correctOption the value for selection.correct_option
     *
     * @mbg.generated Sun Feb 02 17:00:28 CST 2020
     */
    public void setCorrectOption(String correctOption) {
        this.correctOption = correctOption == null ? null : correctOption.trim();
    }
}