package com.wscloudclass.model;

import java.util.Date;

public class SubmitFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_file.file_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Long fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_file.file_name
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_file.file_url
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_file.submit_time
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Date submitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_file.file_size
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Integer fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_file.uid
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_file.file_id
     *
     * @return the value of submit_file.file_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_file.file_id
     *
     * @param fileId the value for submit_file.file_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_file.file_name
     *
     * @return the value of submit_file.file_name
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_file.file_name
     *
     * @param fileName the value for submit_file.file_name
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_file.file_url
     *
     * @return the value of submit_file.file_url
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_file.file_url
     *
     * @param fileUrl the value for submit_file.file_url
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_file.submit_time
     *
     * @return the value of submit_file.submit_time
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_file.submit_time
     *
     * @param submitTime the value for submit_file.submit_time
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_file.file_size
     *
     * @return the value of submit_file.file_size
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_file.file_size
     *
     * @param fileSize the value for submit_file.file_size
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_file.uid
     *
     * @return the value of submit_file.uid
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_file.uid
     *
     * @param uid the value for submit_file.uid
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }
}