package com.wscloudclass.model;

public class UserAnswersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answers.uid
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answers.sel_id
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    private Long selId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answers.uid
     *
     * @return the value of user_answers.uid
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answers.uid
     *
     * @param uid the value for user_answers.uid
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answers.sel_id
     *
     * @return the value of user_answers.sel_id
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    public Long getSelId() {
        return selId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answers.sel_id
     *
     * @param selId the value for user_answers.sel_id
     *
     * @mbg.generated Sun Feb 09 14:40:33 CST 2020
     */
    public void setSelId(Long selId) {
        this.selId = selId;
    }
}