package com.wscloudclass.model;

public class UserFavKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fav.uid
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fav.sel_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    private Long selId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fav.uid
     *
     * @return the value of user_fav.uid
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fav.uid
     *
     * @param uid the value for user_fav.uid
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fav.sel_id
     *
     * @return the value of user_fav.sel_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public Long getSelId() {
        return selId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fav.sel_id
     *
     * @param selId the value for user_fav.sel_id
     *
     * @mbg.generated Wed Feb 12 19:25:47 CST 2020
     */
    public void setSelId(Long selId) {
        this.selId = selId;
    }
}