package com.wscloudclass.model;

public class UserAnswers extends UserAnswersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answers.user_select
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    private Integer userSelect;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answers.user_select
     *
     * @return the value of user_answers.user_select
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public Integer getUserSelect() {
        return userSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answers.user_select
     *
     * @param userSelect the value for user_answers.user_select
     *
     * @mbg.generated Sat Feb 01 19:12:34 CST 2020
     */
    public void setUserSelect(Integer userSelect) {
        this.userSelect = userSelect;
    }
}